name: 'Get Source Version Information'
description: 'Extract version information from source code'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: ./tools/unix/get-source-version.sh ./source/base/version.h github >> $GITHUB_ENV
